---

tigervnc_username: robertdb
tigervnc_groupname: users

# Connecting to tigervnc-server required a password.
# tigervnc_password: vncpass

tigervnc_user_exists: yes
tigervnc_desktop_session: gnome-session
