#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ../terraform
        state: "{{ terraform_state | default('present') }}"
      register: terraform

    - name: add servers to inventory
      add_host:
        name: "{{ item }}"
      loop: "{{ terraform.outputs.cloudtop_hostnames.value }}"

    - name: wait for port 22
      wait_for:
        host: "{{ item }}"
        port: 22
      loop: "{{ terraform.outputs.cloudtop_hostnames.value }}"

- name: setup all nodes
  hosts: all
  become: yes
  gather_facts: yes
  strategy: free

  roles:
    - role: robertdebock.bootstrap
    # Resolving hosts is problematic, using cloud-init.yml.
    # - role: robertdebock.common
    - role: robertdebock.update
    - role: robertdebock.digitalocean_agent
    - role: robertdebock.sysstat
    - role: robertdebock.auto_update
    - role: robertdebock.cron
    - role: robertdebock.ntp
    - role: robertdebock.openssh
    - role: robertdebock.fail2ban
    - role: robertdebock.firewall
    - role: robertdebock.postfix
    - role: robertdebock.users
    - role: robertdebock.gnome
    - role: robertdebock.xrdp
